# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RazzleDazzle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RazzleDazzle

  
  target 'RazzleDazzleTests' do
    inherit! :search_paths
    pod 'Nimble', '~> 8.0'
    pod 'Quick', '~> 2.0'
  end
  
end
